[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = ['cd backend && npm install --production --no-audit --no-fund --prefer-offline --no-optional']

[phases.build]

[start]
cmd = 'cd backend && node server.js'
