[phases.setup]
nixPkgs = ['nodejs_22', 'npm-9_x']

[phases.install]
cmds = ['cd backend && npm ci --only=production --prefer-offline']

[phases.build]
cmds = []

[start]
cmd = 'cd backend && node server.js'
