[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
providers = ["node"]

[deploy]
startCommand = "cd backend && node server.js"
healthcheckPath = "/api/test"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3