[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install --production --no-audit --no-fund"

[build.nixpacksConfig]
providers = ["node"]

[deploy]
startCommand = "cd backend && node server.js"
healthcheckPath = "/api/test"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3