[build]
builder = "NIXPACKS"
buildCommand = "cd frontend/react-app && npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/test"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3