[build]
builder = "NIXPACKS"
[build]
builder = "NIXPACKS"
# Install backend and frontend dependencies, then build the frontend
buildCommand = "cd backend && npm ci && cd ../frontend/react-app && npm ci && npm run build"

[deploy]
#[deploy]
# Start using the repo-level start script which launches the backend
startCommand = "npm start"
healthcheckPath = "/api/test"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3