[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && node server.js"
healthcheckPath = "/api/test"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3