[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
providers = ["node"]

[build.nixpacksConfig.phases.install]
cmds = ["cd backend && npm ci --only=production"]

[build.nixpacksConfig.phases.setup]
aptPkgs = []

[deploy]
startCommand = "cd backend && node server.js"
healthcheckPath = "/api/test"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3